# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Star_Build-Pack-Publish
on:
#  watch:
#    types: [started]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    ##if: github.event == 'watch' && github.actor == github.event.repository.owner.login #only me
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.101
    - name: Build and Pack
      run: dotnet build --configuration Release
    - run: dotnet --version
    - run: dotnet nuget --version
    - run: dotnet nuget push --help
    - uses: actions/upload-artifact@v1
      with:
        name: OsmApiClient.0.0.1-beta.4.nupkg
        path: /home/runner/work/OsmApiClient/OsmApiClient/src/bin/Release/OsmApiClient.*.nupkg
    - name: Nuget publish
      run: dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NugetApiKey}} /home/runner/work/OsmApiClient/OsmApiClient/src/bin/Release/OsmApiClient.*.nupkg

